### ISSUE TITLE
Cursor appearance not changing on Windows 10

### ISSUE THREAD

**Issue by Eric2-Praxinos** [ultralight-ux/ultralight-quick-start#2]
Hi,

Using the quickstart project, my mouse cursor does not update when I move it inside the window.
Like, when I move it over a link, it should change to a hand, but it doesn't.
Moreover, if I resize the main window, the cursor changes to a double arrow, but then it does not change back to the classic pointer cursor.

The only change I made on the quickstart project was pointing to "http://www.google.com"

**Comment by adamjs** [comment]
Hello, you just have to handle `ViewListener::OnChangeCursor` and pass that cursor to `Window::SetCursor`. (The View does not automatically set the cursor for the Window)

I've updated the code to demonstrate this.
